@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjQ4ODQ3Mjc2fQ.zqfGtzQpcN0CecsK2KF5ApCOpzLpRJeM7AxeUfsRdvs
#Lou

@jwt_S = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2NDg4NDcyNDl9.MD0-G124G7T5fRJ9YW2WpF5V4FshfB2R9uyoFJj0YpY

### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Hello Kitty Rice Cooker",
  "price": 32,
  "image_url": "https://i5.walmartimages.com/asr/8fbcad21-ef6e-43a7-8308-25411b44436d_1.2be433602da0fe22a1efb4b2170cc819.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
  "description": "makes the cutest rice!"
}

### PRODUCTS SHOW
GET http://localhost:3000/products/1.json

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
  "name": "Hello Kitty Rice Cooker",
  "price": 100
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/2.json

### USERS CREATE (signup) 
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "lou",
  "email": "lou@example.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": true
}

### USERS DESTROY
DELETE http://localhost:3000/users/3.json

### SESSIONS CREATE (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "lou@example.com",
  "password": "password"
}

### ORDERS CREATE (login)
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 10,
  "quantity": 200
}

### ORDERS SHOW
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}

### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt_S}}

### CARTED-PRODUCT CREATE
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt_S}}
Content-Type: application/json

{
  "product_id": 7,
  "quantity": 52
}

### CARTED-PRODUCT INDEX
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt_S}}

### CARTED-PRODUCT DESTROY
DELETE http://localhost:3000/carted_products/5.json
Authorization: Bearer {{jwt_S}}
