### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Hello Kitty Rice Cooker",
  "price": 32,
  "image_url": "https://i5.walmartimages.com/asr/8fbcad21-ef6e-43a7-8308-25411b44436d_1.2be433602da0fe22a1efb4b2170cc819.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
  "description": "makes the cutest rice!"
}

### PRODUCTS SHOW
GET http://localhost:3000/products/1.json

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
  "name": "Hello Kitty Rice Cooker",
  "price": 100
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/2.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "luna",
  "email": "luna@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "luna@test.com",
  "password": "password"
}

### Order create (login)
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgwNTgxNTl9.Hy0JSbC9zXjGWiFLRYMDNcST90Cs_BJK9ur_TAlZZMg

{
  "product_id": 10,
  "quantity": 200
}

### ORDERS SHOW
GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNTY2NTJ9.ce1naz3EX-SUjAlfPssUdVu7uS30RL0IZjlZvzbKjBs

### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNTY2NTJ9.ce1naz3EX-SUjAlfPssUdVu7uS30RL0IZjlZvzbKjBs